apiVersion: apps/v1
kind: Deployment
metadata:
  name: appone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appone-pod
  template:
    metadata:
      labels:
        app: appone-pod
    spec:
      hostname: appone
      serviceAccountName: default
      containers:
        - name: appone
          image: docker.io/juanfbl93/app_one:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
      imagePullSecrets:
        - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appone
  name: appone
spec:
  ports:
    - port: 8080
      name: high
      protocol: TCP
      targetPort: 3000
  selector:
    app: appone-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptwo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apptwo-pod
  template:
    metadata:
      labels:
        app: apptwo-pod
    spec:
      hostname: apptwo
      serviceAccountName: default
      containers:
        - name: apptwo
          image: juanfbl93/app_two:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apptwo
  name: apptwo
spec:
  ports:
    - port: 8080
      name: high
      protocol: TCP
      targetPort: 3001
  selector:
    app: apptwo-pod