---
apiVersion: v1
kind: Service
metadata:
  name: appone
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: apptwo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001